import { Case, Counsel, Appointment, Transaction, Court, CaseType } from '../types';

export const generateMockData = () => {
  const mockCases: Case[] = [
    {
      id: '1',
      clientName: 'Sanjay durgadas gaware',
      clientEmail: 'sanjay@example.com',
      clientMobile: '9876543210',
      clientAlternateNo: '9876543211',
      fileNo: '00384',
      stampNo: '',
      regNo: '',
      partiesName: 'Sanjay durgadas gaware',
      district: 'Mumbai',
      caseType: 'Civil',
      court: 'High Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Smith',
      additionalDetails: 'Important civil case',
      feesQuoted: 50000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2023-07-12'),
      filingDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'favor',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '2',
      clientName: 'Anil g tatawar',
      clientEmail: 'anil@example.com',
      clientMobile: '9876543212',
      clientAlternateNo: '9876543213',
      fileNo: '00029',
      stampNo: '',
      regNo: '2899/2021',
      partiesName: 'Anil g tatawar',
      district: 'Delhi',
      caseType: 'Criminal',
      court: 'District Court',
      onBehalfOf: 'Defendant',
      noResp: '2',
      opponentLawyer: 'Advocate Johnson',
      additionalDetails: 'Criminal case details',
      feesQuoted: 75000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2022-02-17'),
      filingDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
      circulationStatus: 'non-circulated',
      interimRelief: 'against',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '3',
      clientName: 'Babasaheb langade',
      clientEmail: 'babasaheb@example.com',
      clientMobile: '9876543214',
      clientAlternateNo: '9876543215',
      fileNo: '00351',
      stampNo: '17006/2019',
      regNo: '8217/2019',
      partiesName: 'Babasaheb langade',
      district: 'Bangalore',
      caseType: 'Commercial',
      court: 'Commercial Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Williams',
      additionalDetails: 'Commercial dispute',
      feesQuoted: 100000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2022-04-22'),
      filingDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'none',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '4',
      clientName: 'Rajabhu phad',
      clientEmail: 'rajabhu@example.com',
      clientMobile: '9876543216',
      clientAlternateNo: '9876543217',
      fileNo: '00323',
      stampNo: '',
      regNo: '8934/2018',
      partiesName: 'Rajabhu phad',
      district: 'Pune',
      caseType: 'Civil',
      court: 'District Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Brown',
      additionalDetails: 'Property dispute',
      feesQuoted: 60000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2021-12-17'),
      filingDate: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'none',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '5',
      clientName: 'Bhagyashri satyanarayana naige',
      clientEmail: 'bhagyashri@example.com',
      clientMobile: '9876543218',
      clientAlternateNo: '9876543219',
      fileNo: '00329',
      stampNo: '',
      regNo: '3589/2020',
      partiesName: 'Bhagyashri satyanarayana naige',
      district: 'Hyderabad',
      caseType: 'Family',
      court: 'Family Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Davis',
      additionalDetails: 'Family law case',
      feesQuoted: 45000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2022-01-07'),
      filingDate: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'favor',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '6',
      clientName: 'Swaraj kala kendra',
      clientEmail: 'swaraj@example.com',
      clientMobile: '9876543220',
      clientAlternateNo: '9876543221',
      fileNo: '00294',
      stampNo: '',
      regNo: '282 of 2021',
      partiesName: 'Swaraj kala kendra',
      district: 'Chennai',
      caseType: 'Civil',
      court: 'High Court',
      onBehalfOf: 'Defendant',
      noResp: '2',
      opponentLawyer: 'Advocate Miller',
      additionalDetails: 'Contract dispute',
      feesQuoted: 80000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2022-01-12'),
      filingDate: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'none',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '7',
      clientName: 'Rajabhau phad',
      clientEmail: 'rajabhau@example.com',
      clientMobile: '9876543222',
      clientAlternateNo: '9876543223',
      fileNo: '00224',
      stampNo: '',
      regNo: '1534 of 2021',
      partiesName: 'Rajabhau phad',
      district: 'Kolkata',
      caseType: 'Criminal',
      court: 'District Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Wilson',
      additionalDetails: 'Criminal case',
      feesQuoted: 55000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2021-08-26'),
      filingDate: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'against',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '8',
      clientName: 'Kishor dasram dagwale',
      clientEmail: 'kishor@example.com',
      clientMobile: '9876543224',
      clientAlternateNo: '9876543225',
      fileNo: '00',
      stampNo: '',
      regNo: '5104/2009',
      partiesName: 'Kishor dasram dagwale',
      district: 'Jaipur',
      caseType: 'Civil',
      court: 'District Court',
      onBehalfOf: 'Defendant',
      noResp: '2',
      opponentLawyer: 'Advocate Moore',
      additionalDetails: 'Land dispute',
      feesQuoted: 70000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2021-01-01'),
      filingDate: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'none',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '9',
      clientName: '21st century infra fele itd. &...',
      clientEmail: 'infra@example.com',
      clientMobile: '9876543226',
      clientAlternateNo: '9876543227',
      fileNo: '00',
      stampNo: '',
      regNo: '',
      partiesName: '21st century infra fele itd.',
      district: 'Lucknow',
      caseType: 'Commercial',
      court: 'Commercial Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Taylor',
      additionalDetails: 'Infrastructure contract',
      feesQuoted: 120000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2021-01-01'),
      filingDate: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'none',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '10',
      clientName: 'Dr. trimbak bathe',
      clientEmail: 'trimbak@example.com',
      clientMobile: '9876543228',
      clientAlternateNo: '9876543229',
      fileNo: '00',
      stampNo: '',
      regNo: 'wp-6830/07',
      partiesName: 'Dr. trimbak bathe',
      district: 'Nagpur',
      caseType: 'Civil',
      court: 'High Court',
      onBehalfOf: 'Plaintiff',
      noResp: '1',
      opponentLawyer: 'Advocate Anderson',
      additionalDetails: 'Writ petition',
      feesQuoted: 90000,
      status: 'closed',
      stage: 'disposed',
      nextDate: new Date('2021-01-01'),
      filingDate: new Date(Date.now() - 350 * 24 * 60 * 60 * 1000),
      circulationStatus: 'circulated',
      interimRelief: 'none',
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const mockCounsel: Counsel[] = [
    {
      id: '1',
      name: 'Advocate Smith',
      email: 'smith@example.com',
      mobile: '9876543220',
      address: '123 Law Street, Mumbai',
      details: 'Senior advocate with 20 years experience',
      totalCases: 45,
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '2',
      name: 'Advocate Johnson',
      email: 'johnson@example.com',
      mobile: '9876543221',
      address: '456 Court Lane, Delhi',
      details: 'Criminal law specialist',
      totalCases: 32,
      createdBy: 'admin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const mockAppointments: Appointment[] = [
    {
      id: '1',
      date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
      time: '10:00 AM',
      user: 'John Doe',
      client: 'Sanjay durgadas gaware',
      details: 'Case discussion',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '2',
      date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      time: '2:00 PM',
      user: 'Jane Smith',
      client: 'Rajesh Kumar',
      details: 'Document review',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  const mockTransactions: Transaction[] = [
    {
      id: '1',
      amount: 50000,
      status: 'received',
      paymentMode: 'cash',
      receivedBy: 'John Doe',
      confirmedBy: 'Admin',
      caseId: '1',
      createdAt: new Date(),
    },
    {
      id: '2',
      amount: 25000,
      status: 'pending',
      paymentMode: 'upi',
      receivedBy: 'Jane Smith',
      confirmedBy: 'Pending',
      caseId: '2',
      createdAt: new Date(),
    },
  ];

  const mockCourts: Court[] = [
    { id: '1', name: 'High Court', createdAt: new Date() },
    { id: '2', name: 'District Court', createdAt: new Date() },
    { id: '3', name: 'Commercial Court', createdAt: new Date() },
    { id: '4', name: 'Supreme Court', createdAt: new Date() },
  ];

  const mockCaseTypes: CaseType[] = [
    { id: '1', name: 'Civil', createdAt: new Date() },
    { id: '2', name: 'Criminal', createdAt: new Date() },
    { id: '3', name: 'Commercial', createdAt: new Date() },
    { id: '4', name: 'Family', createdAt: new Date() },
  ];

  return {
    cases: mockCases,
    counsel: mockCounsel,
    appointments: mockAppointments,
    transactions: mockTransactions,
    courts: mockCourts,
    caseTypes: mockCaseTypes,
  };
};
